version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: artesanias_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - artesanias_net

  backend:
    build: ./backend
    container_name: artesanias_backend
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - artesanias_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: artesanias_frontend
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - artesanias_net

  nginx:
    image: nginx:alpine
    container_name: artesanias_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./nginx/certs:/etc/nginx/certs
      - ./backend/uploads:/var/www/uploads
    command: /bin/sh -c "envsubst < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - artesanias_net

networks:
  artesanias_net:
    driver: bridge

volumes:
  postgres_data: 